run_tests:
  stage: test
  script:
    - echo "Running tests..."
    - echo "All tests passed! :3"

build_image:
  stage: build
  before_script:
    - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASSWORD"
  script:
    - docker build -t dustycs/k8s-web-to-nginx:v3 k8s-web-to-nginx 
    - docker push dustycs/k8s-web-to-nginx:v3